const app=document.querySelector('#app'),title=document.querySelector('#title');
let page='overview',snapshot=null;const events=[];
const esc=v=>String(v??'未检测到').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const field=(k,v)=>'<div class="env"><small>'+esc(k)+'</small><strong>'+esc(v)+'</strong></div>';
const card=(name,body)=>'<section class="card"><div class="card-head"><h2>'+name+'</h2></div>'+body+'</section>';
function render(){const s=snapshot;title.textContent=({overview:'节点总览',task:'当前任务',engine:'H3 环境',logs:'检测日志',settings:'设置'})[page];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(!s){app.textContent='正在读取本机状态…';return}
const sys=s.comfy?.system||{},argv=sys.argv||[],arg=k=>argv.includes(k)?argv[argv.indexOf(k)+1]:null;
const gpu=s.gpu?s.gpu.split('\n').map(row=>{const a=row.split(',').map(x=>x.trim());return card(esc(a[0]),field('GPU 使用率',a[1]+'%')+field('显存',a[2]+' / '+a[3]+' MiB')+field('温度',a[4]+' ℃'))}).join(''):card('GPU','未检测到 GPU 数据');
const env=card('实际运行环境',field('ComfyUI 版本',sys.comfyui_version)+field('Python',sys.python_version)+field('安装目录',arg('--base-directory'))+field('输出目录',arg('--output-directory'))+field('PyTorch',sys.pytorch_version)+field('H3 加载状态','尚未接入模型加载检测'));
const q=s.queue;const tasks=card('本机 ComfyUI 任务',q?'<p>执行中 '+q.queue_running.length+' · 本机排队 '+q.queue_pending.length+'</p>'+[...q.queue_running,...q.queue_pending].map(t=>field('ComfyUI Prompt ID',t[1])).join('')+'<p class="muted">Scheduler 任务详情、来源、进度和今日统计尚未接入。</p>':'无法读取本机任务队列');
const logs=card('本客户端检测记录',events.map(e=>'<div class="log-line">'+esc(e)+'</div>').join(''));
const status=card('连接状态',field('Scheduler 健康接口',s.scheduler?'可访问':'不可访问')+field('ComfyUI',s.comfyui?'可访问':'不可访问')+field('Core Tunnel',s.managed?.fresh?s.managed.components.core?.state:'守护进程无响应')+field('Admin Tunnel',s.managed?.fresh?s.managed.components.admin?.state:'未知')+field('Worker',s.managed?.fresh?s.managed.workerState:'守护进程无响应')+field('Agent',s.managed?.agent?.online?'Online':s.managed?.agent?.state||'Starting')+field('最近心跳',s.managed?.agent?.lastHeartbeat)+field('本地 ComfyUI 地址',s.managed?.localComfy?.url)+field('远程隧道端口',s.managed?.components.core?.target?.remotePort)+field('注册错误',s.enrollmentError||'无')+field('核心重连次数',s.managed?.components.core?.reconnects||0)+field('最近连接成功',s.managed?.components.core?.lastSuccess)+field('最近隧道错误',s.managed?.components.core?.lastError||'无')+field('守护运行时长',s.managed?.fresh?s.managed.uptimeSeconds+' 秒':'未知')+field('云端队列数',s.gateway?.queue_depth)+field('Worker ID',s.managed?.agent?.lease?.worker_id));
app.innerHTML='<div class="grid">'+(page==='overview'?status+tasks+gpu+card('系统资源',field('CPU 使用率',s.cpu==null?'采样中':s.cpu+'%')+field('内存',s.memory?s.memory.used+' / '+s.memory.total+' GiB':null)):page==='task'?tasks:page==='engine'?env:page==='logs'?logs:card('连接配置','<p>ComfyUI：自动探测进程参数并验证 /system_stats</p><p>管理网关：自动寻找可用端口；核心反向端口：由 Scheduler 分配</p><p>已接入设备注册、独立 Agent 心跳、云端隧道验证与后台自动恢复。</p>'))+'</div>';
}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelector('#settings').onclick=()=>{page='settings';render()};
document.querySelector('.worker-pill span').textContent='本机节点';document.querySelector('.worker-pill b').textContent='检测中';document.querySelector('header small').textContent='本机生成节点';document.querySelector('.sync').textContent='等待检测';render();
