(()=>{
 const api=window.vimoUpdater;if(!api)return;
 const panel=document.createElement('section');panel.className='worker-update-panel';panel.hidden=true;panel.setAttribute('aria-label','Vimo Worker 更新');panel.innerHTML='<button class="update-close" id="update-later" aria-label="稍后更新">稍后</button><h3 id="update-title">检查更新</h3><p id="update-versions"></p><pre id="update-notes"></pre><progress id="update-progress" max="100" hidden></progress><p id="update-detail" role="status"></p><div class="update-actions"><button id="update-cancel" hidden>取消下载</button><button id="update-details">查看详情</button><button id="update-now" class="update-primary" hidden>立即更新</button></div>';
 document.body.append(panel);const el=id=>document.getElementById(id),nav=el('update-check-nav');let current={status:'idle'},previous;
 const size=n=>((n||0)/1024/1024).toFixed(1)+' MB';
 function render(s){current=s;document.querySelectorAll('[data-app-version]').forEach(e=>e.textContent=s.currentVersion);const available=s.status==='available'||(s.status==='error'&&s.latestVersion),ready=s.status==='downloaded',downloading=s.status==='downloading';nav.disabled=false;nav.textContent=s.status==='checking'?'↻ 正在检查':ready?'✓ 更新待安装':'↻ 检查更新';if(['available','downloaded'].includes(s.status)&&previous!==s.status)panel.hidden=false;el('update-title').textContent=ready?'更新已准备就绪':downloading?'正在下载更新':available?'发现新版本':'检查更新';el('update-versions').textContent=`当前版本：${s.currentVersion}　最新版本：${s.latestVersion||'—'}`;el('update-notes').textContent=s.notes||'';el('update-notes').hidden=!s.notes;el('update-progress').hidden=!downloading;el('update-progress').value=s.progress?.percent||0;el('update-detail').textContent=downloading&&s.progress?`${s.progress.percent.toFixed(1)}% · ${size(s.progress.transferred)} / ${size(s.progress.total)} · ${size(s.progress.bytesPerSecond)}/s`:s.message||'';el('update-now').hidden=!(available||ready);el('update-now').textContent=ready?'维护升级说明':s.status==='error'?'重试下载':'立即更新';el('update-cancel').hidden=!downloading;previous=s.status}
 const safe=fn=>()=>Promise.resolve().then(fn).catch(()=>{el('update-detail').textContent='更新操作失败，请稍后重试。'});
 nav.onclick=safe(async()=>{panel.hidden=false;render(await api.check())});el('update-now').onclick=safe(()=>current.status==='downloaded'?api.install():api.download());el('update-cancel').onclick=safe(()=>api.cancel());el('update-details').onclick=safe(()=>api.details());el('update-later').onclick=()=>{panel.hidden=true};api.subscribe(render);api.state().then(render).catch(()=>{});
})();
