'use strict';
const $=s=>document.querySelector(s),BASE='/vimo-admin/api';
const pages={overview:'总览',tasks:'任务',workers:'Workers',queue:'队列',users:'用户',keys:'API Keys',usage:'用量',logs:'日志',settings:'设置'};
const icons=['◫','☷','▤','≋','♙','⚿','▥','≡','⚙'];
const statuses={queued:'排队中',running:'运行中',completed:'已完成',failed:'失败',cancelled:'已取消'};
let state=null,route='overview',statusFilter='all',query='',loggedIn=false,refreshTimer=null,requestBusy=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=t=>t?new Date(t*1000).toLocaleString('zh-CN',{hour12:false}):'—';
const elapsed=t=>{const n=Math.max(0,Math.floor((t.finished_at||Date.now()/1000)-t.created_at));return `${Math.floor(n/60)}m ${n%60}s`};
const userName=id=>state?.users.find(u=>u.id===id)?.username||id||'—';
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',4000)}
async function api(path,method='GET',body){const r=await fetch(BASE+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json','X-Vimo-Admin':'1'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>({detail:'服务器返回无法解析的响应'}));if(!r.ok){if(r.status===401&&path!='/login'){loggedIn=false;loginView()}throw Error(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail||'请求失败'))}return d}
function badge(s){return `<span class="badge ${esc(s)}">${esc(statuses[s]||({online:'在线',offline:'离线',active:'启用',disabled:'停用'}[s])||s)}</span>`}
function heading(t,p,actions=''){return `<div class="heading"><div><h1>${t}</h1><p>${p}</p></div><div class="actions">${actions}</div></div>`}
function metric(label,value,sub,action){return `<${action?'button':'div'} class="metric" ${action?`onclick="${action}"`:''}><div class="metricTop">${label}</div><strong>${value??'—'}</strong><small>${sub}</small></${action?'button':'div'}>`}
function table(headers,rows){return `<section class="panel"><div class="tableWrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}" class="empty">暂无记录</td></tr>`}</tbody></table></div></section>`}
function nav(){let i=0;$('#nav').innerHTML=Object.entries(pages).map(([id,title])=>`${i===0?'<label>运行管理</label>':i===4?'<label>接入管理</label>':i===7?'<label>系统管理</label>':''}<a href="#${id}" title="${title}" class="${id===route?'active':''}"><i>${icons[i++]}</i><span>${title}</span></a>`).join('');$('#crumb').textContent=pages[route];$('.headerRight').innerHTML=`<span class="demo">实时服务</span><button onclick="refresh()">↻ 刷新</button><button onclick="logout()">退出</button>`}
function loginView(){clearInterval(refreshTimer);$('#nav').innerHTML='';$('.headerRight').innerHTML='<span class="demo">管理员入口</span>';$('#app').innerHTML=`<section class="panel loginPanel"><div class="brand"><b>v</b> vimo <span>ADMIN</span></div><h1>登录管理平台</h1><p class="note">使用独立管理员账号访问真实调度数据。</p><form class="form" onsubmit="login(event)"><label>账号<input name="username" autocomplete="username" required value="admin"></label><label>密码<input type="password" name="password" autocomplete="current-password" required></label><button class="primary">登录</button><p id="loginError" class="note" role="alert"></p></form></section>`}
async function login(e){e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('/login','POST',Object.fromEntries(new FormData(e.target)));e.target.reset();loggedIn=true;await refresh();refreshTimer=setInterval(()=>refresh(false),15000)}catch(err){$('#loginError').textContent=err.message}finally{button.disabled=false}}
async function logout(){try{await api('/logout','POST');loggedIn=false;state=null;loginView()}catch(e){toast(e.message)}}
async function refresh(showError=true){if(requestBusy)return;requestBusy=true;try{state=await api('/snapshot');loggedIn=true;$('.sidebottom').innerHTML=`<span class="dot"></span> 真实网关<small>单机 H3 · 管理员</small><div class="profile"><b>A</b><div>Administrator<small>最后更新 ${new Date(state.at*1000).toLocaleTimeString('zh-CN')}</small></div></div>`;if(!$('#detail').open&&(!document.activeElement||!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)))await render();$('footer').innerHTML=`Vimo Admin <span>已连接现有 H3 网关</span><span>UTC+8 · ${date(state.at)}</span>`}catch(e){if(showError)toast(e.message);if(loggedIn)$('footer').textContent='连接异常，当前为旧数据。最后成功更新：'+date(state?.at)}finally{requestBusy=false}}
function taskTable(items){return table(['任务 ID','用户 / 来源','模型','状态 / 阶段','进度','耗时','创建时间'],items.map(t=>`<tr tabindex="0" onclick="taskDetail('${esc(t.id)}')" onkeydown="if(event.key==='Enter')taskDetail('${esc(t.id)}')"><td>${esc(t.id.slice(0,22))}…</td><td>${esc(userName(t.user_id))}<small>${esc(t.source||'现有网关')}</small></td><td>H3</td><td>${badge(t.status)}<small>${esc(t.progress?.stage||'')}</small></td><td>${t.progress?.percent==null?'—':`${esc(t.progress.percent)}%`}</td><td>${elapsed(t)}</td><td>${date(t.created_at)}</td></tr>`))}
function goTasks(s){statusFilter=s;location.hash='tasks';if(route==='tasks')render()}
function overview(){const w=state.worker;return heading('总览','真实任务与生成节点状态，每 15 秒刷新')+`<div class="metrics">${metric('运行中任务',state.counts.running,'当前执行','goTasks(\'running\')')}${metric('排队任务',state.counts.queued,'等待执行','location.hash=\'queue\'')}${metric('生成节点',w.online?'在线':'离线',w.paused?'已暂停接单':'接单开关已开启','location.hash=\'workers\'')}${metric('今日失败任务',state.today_failed,'按任务结束时间统计','goTasks(\'failed\')')}</div>${!w.online?'<div class="alert"><b>⚠</b>节点未就绪。请在 Workers 页面查看 Agent、Tunnel 和 ComfyUI 的独立状态。</div>':''}${w.paused?'<div class="alert">已暂停接单：当前任务继续执行，队列等待管理员恢复。</div>':''}<div class="metrics">${metric('今日完成',state.today_completed,'北京时间今日')}${metric('今日成功率',state.success_rate==null?'—':state.success_rate+'%','已完成 / 已完成与失败')}${metric('今日 API 请求',state.usage.requests,'从本次接入开始记录')}${metric('API 用户',state.users.length,'含原有 Studio 服务账号')}</div><div class="panelTitle"><h2>最近任务</h2><button class="link" onclick="goTasks('all')">全部任务 →</button></div>${taskTable(state.tasks.slice(0,10))}`}
function taskPage(queue=false){const items=state.tasks.filter(t=>(queue?t.status==='queued':statusFilter==='all'||t.status===statusFilter)&&(`${t.id} ${userName(t.user_id)}`.toLowerCase().includes(query.toLowerCase())));return heading(queue?'调度队列':'任务管理',queue?'排队任务按现有网关顺序执行':'查看任务详情、执行事件与输入参数')+(!queue?`<div class="tabs">${Object.entries({all:'全部',...statuses}).map(([s,l])=>`<button class="${statusFilter===s?'active':''}" onclick="statusFilter='${s}';render()">${l}</button>`).join('')}</div>`:'')+`<div class="filters"><input type="search" aria-label="搜索任务" placeholder="任务 ID 或用户" value="${esc(query)}" oninput="query=this.value;updateTaskList()"><span class="note">${queue?(state.worker.paused?'等待恢复接单':!state.worker.online?'等待生成节点连接':'等待可用生成节点'):''}</span></div><div id="taskList">${taskTable(items)}</div>`}
function updateTaskList(){const list=state.tasks.filter(t=>(route==='queue'?t.status==='queued':statusFilter==='all'||t.status===statusFilter)&&(`${t.id} ${userName(t.user_id)}`.toLowerCase().includes(query.toLowerCase())));$('#taskList').innerHTML=taskTable(list)}
function show(content){$('#detailContent').innerHTML=content;if(!$('#detail').open)$('#detail').showModal()}
function closeDetail(){$('#detail').close();$('#detailContent').innerHTML=''}
function detailHead(title){return `<div class="detailHead"><h2>${title}</h2><button aria-label="关闭" onclick="closeDetail()">✕</button></div>`}
async function taskDetail(id){try{const t=await api('/tasks/'+encodeURIComponent(id));show(detailHead('任务详情')+`<div class="detailBody"><p class="taskId">${esc(t.id)}</p>${badge(t.status)}<div class="fields">${[['用户',userName(t.user_id)],['模型','H3'],['创建',date(t.created_at)],['开始',date(t.started_at)],['结束',date(t.finished_at)],['来源',t.source||'原有网关']].map(([k,v])=>`<div><small>${k}</small><strong>${esc(v)}</strong></div>`).join('')}</div>${t.error?`<div class="alert">${esc(t.error)}</div>`:''}<div class="actions">${t.status==='queued'?`<button class="danger" onclick="confirmAction('取消这个排队任务？','/tasks/${esc(t.id)}/cancel')">取消任务</button>`:''}${t.status==='failed'?`<button class="primary" onclick="confirmAction('创建新的重试任务？原失败记录将保留。','/tasks/${esc(t.id)}/retry')">重新执行</button>`:''}</div>${t.status==='running'?'<p class="note">当前版本仅支持取消排队任务，不直接中断 ComfyUI 正在执行的工作。</p>':''}<h3>执行事件</h3><div class="timeline">${t.events.map(e=>`<div class="event">${esc(e.kind)}<small>${date(e.at)}</small></div>`).join('')||'<p class="note">历史任务未记录阶段事件。</p>'}</div><h3>输入参数</h3><pre>${esc(JSON.stringify(t.request,null,2))}</pre>${t.parent_task_id?`<p class="note">原任务：${esc(t.parent_task_id)}</p>`:''}${t.retry_task_id?`<p class="note">重试任务：${esc(t.retry_task_id)}</p>`:''}</div>`)}catch(e){toast(e.message)}}
function confirmAction(message,path,body,method='POST'){show(detailHead('确认操作')+`<div class="detailBody"><p>${esc(message)}</p><p class="note">此操作会修改真实服务器数据。</p><div class="actions"><button id="confirm" class="primary">确认</button><button onclick="closeDetail()">返回</button></div></div>`);$('#confirm').onclick=async()=>{const b=$('#confirm');b.disabled=true;try{await api(path,method,body);closeDetail();await refresh();toast('服务器已确认操作')}catch(e){toast(e.message);b.disabled=false}}}
async function workers(){
 const rows=await api('/workers'),w=state.worker;
 return heading('Workers','设备注册、隧道和引擎健康状态，每 15 秒刷新')+
 table(['Worker ID','机器名称','Worker 版本','最新稳定版','更新状态','运行状态','Agent','Tunnel','ComfyUI','GPU','远程端口','最近心跳','最近错误'],rows.map(x=>`<tr><td>${esc(x.worker_id)}</td><td>${esc(x.hostname||'—')}</td><td>${esc(x.workerVersion||'未上报')}</td><td>${esc(x.latestVersion||'暂未获取')}</td><td>${x.updateAvailable===true?'待更新':x.updateAvailable===false?'已是最新':'待确认'}<br><small>${esc(x.updateState||'unknown')}</small></td><td>${esc(x.state)}</td><td>${x.agent_online?'Online':'Offline'}</td><td>${x.tunnel_online?'Online':'Offline'}</td><td>${x.comfy_ready?'Ready':'Offline'}</td><td>${x.gpu_ready?'Ready':'Not Ready'}</td><td>${esc(x.tunnel_port)}</td><td>${date(x.last_heartbeat)}</td><td>${esc(x.last_error||'—')}</td></tr>`))+
 `<p class="note">只有心跳有效、隧道可访问、ComfyUI 健康检查通过且 GPU 可用，才会显示 Ready。现有任务队列仍由已配置的主节点执行。</p><div class="actions"><button onclick="confirmAction('${w.paused?'恢复队列调度？':'暂停分配新任务？当前任务继续执行。'}','/worker',{enabled:${w.paused}})">${w.paused?'恢复接单':'暂停接单'}</button></div><div class="panelTitle"><h2>正在执行</h2></div>${taskTable(state.tasks.filter(t=>t.status==='running'))}`;
}

async function users(){let html=heading('账号管理','Desktop、Worker 与开发者 API 用户分别管理');for(const pool of ['desktop','worker']){const rows=await api('/client-accounts/'+pool);html+=heading(pool==='desktop'?'Desktop 创作端账号':'Worker 算力端账号','独立账号池',`<button class="primary" onclick="clientAccountForm('${pool}')">创建账号</button>`)+table(['账号','状态','操作'],rows.map(a=>`<tr><td>${esc(a.username)}</td><td>${badge(a.enabled?'active':'disabled')}</td><td><button onclick="confirmAction('修改账号状态并撤销登录？','/client-accounts/${pool}/${a.id}',{enabled:${!a.enabled}},'PATCH')">${a.enabled?'停用':'启用'}</button><button onclick="clientAccountForm('${pool}','${a.id}')">重置密码</button></td></tr>`));}const devices=await api('/account-devices');html+=heading('Worker 设备归属','首次登录登记设备；设备转让前需解除绑定')+table(['设备名称','所属账号 ID','最近登记','操作'],devices.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.account_id)}</td><td>${date(x.last_seen)}</td><td><button onclick="confirmAction('解除设备绑定？','/account-devices/${x.installation_id}',{},'DELETE')">解除绑定</button></td></tr>`));return html+heading('开发者 API 用户','继续使用原有 API Key',`<button onclick="userForm()">创建 API 用户</button>`)+table(['账号','状态'],state.users.map(u=>`<tr><td>${esc(u.username)}</td><td>${badge(u.enabled?'active':'disabled')}</td></tr>`));}
function clientAccountForm(pool,id=''){show(detailHead(id?'重置密码':'创建 '+pool+' 账号')+`<div class="detailBody"><form class="form" onsubmit="saveClientAccount(event,'${pool}','${id}')">${id?'':'<label>账号<input name="username" required pattern="[A-Za-z0-9_-]{3,40}" maxlength="40"></label>'}<label>密码<input name="password" type="password" autocomplete="new-password" required minlength="12" maxlength="200"></label><p>至少12位密码；两个客户端账号互不通用。</p><button class="primary">保存</button></form></div>`);}
async function saveClientAccount(e,pool,id){e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('/client-accounts/'+pool+(id?'/'+id:''),id?'PATCH':'POST',Object.fromEntries(new FormData(e.target)));e.target.reset();closeDetail();await refresh();toast('账号已保存')}catch(err){toast(err.message)}finally{button.disabled=false}}
function userForm(){show(detailHead('创建 API 用户')+`<div class="detailBody"><form class="form" onsubmit="createUser(event)"><label>用户名<input name="username" required pattern="[A-Za-z0-9_\-]{3,40}" placeholder="3–40 位字母、数字、下划线"></label><label>邮箱<input name="email" type="email"></label><button class="primary">创建用户</button></form></div>`)}
async function createUser(e){e.preventDefault();try{await api('/users','POST',Object.fromEntries(new FormData(e.target)));closeDetail();await refresh();toast('用户已创建')}catch(err){toast(err.message)}}
async function keys(){const list=await api('/keys');return heading('API Keys','完整密钥只在创建时显示一次，数据库仅保存哈希与脱敏值',`<button class="primary" onclick="keyForm()">＋ 创建 API Key</button>`)+table(['名称 / 密钥','所属用户','并发 / RPM / 每日任务','有效期','状态','操作'],list.map(k=>`<tr><td>${esc(k.name)}<small>${esc(k.masked)}</small></td><td>${esc(userName(k.user_id))}</td><td>${k.max_concurrency} / ${k.requests_per_minute} / ${k.daily_limit}</td><td>${k.expires_at?date(k.expires_at):'长期'}</td><td>${badge(k.enabled?'active':'disabled')}</td><td><button onclick="confirmAction('${k.enabled?'禁用':'启用'}此密钥？','/keys/${k.id}',{enabled:${!k.enabled}},'PATCH')">${k.enabled?'禁用':'启用'}</button></td></tr>`))+`<p class="note">当前模型：H3。原有 Studio 服务密钥继续兼容，不在此列表展示。</p>`}
function keyForm(){show(detailHead('创建 API Key')+`<div class="detailBody"><form class="form" onsubmit="createKey(event)"><label>名称<input name="name" required maxlength="80"></label><label>所属用户<select name="user_id">${state.users.filter(u=>u.enabled).map(u=>`<option value="${u.id}">${esc(u.username)}</option>`).join('')}</select></label><label>模型<input disabled value="H3"></label><label>最大并发任务<input name="max_concurrency" type="number" min="1" max="50" value="2" required></label><label>每分钟请求数<input name="requests_per_minute" type="number" min="1" max="1000" value="30" required></label><label>每日创建任务额度<input name="daily_limit" type="number" min="1" max="100000" value="100" required></label><label>有效期（留空为长期）<input name="expires_at" type="datetime-local"></label><button class="primary">创建密钥</button></form></div>`)}
async function createKey(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));for(const k of ['max_concurrency','requests_per_minute','daily_limit'])d[k]=Number(d[k]);d.expires_at=d.expires_at?new Date(d.expires_at).getTime()/1000:null;try{const r=await api('/keys','POST',d);show(detailHead('密钥已创建')+`<div class="detailBody"><p class="note">请立即保存。关闭后无法再次查看完整密钥。</p><pre class="taskId">${esc(r.key)}</pre><button id="copyKey">复制密钥</button></div>`);$('#copyKey').onclick=()=>navigator.clipboard.writeText(r.key).then(()=>toast('已复制')).catch(()=>toast('请手动选择并复制'));await render()}catch(err){toast(err.message)}}
async function usage(){const list=await api('/usage');return heading('用量统计','北京时间今日 · 从管理功能接入后开始采集')+`<div class="metrics">${metric('API 请求',state.usage.requests,'包含创建、查询和项目操作')}${metric('失败请求',state.usage.errors||0,'HTTP 状态码 ≥ 400')}${metric('完成任务',state.today_completed,'今日完成')}${metric('失败任务',state.today_failed,'今日失败')}</div>`+table(['用户','Key ID','请求数','失败请求','平均响应时间'],list.map(x=>`<tr><td>${esc(userName(x.user_id))}</td><td>${esc(x.key_id||'未认证')}</td><td>${x.requests}</td><td>${x.errors||0}</td><td>${(x.duration*1000).toFixed(0)} ms</td></tr>`))}
async function logs(){const list=await api('/logs');return heading('事件日志','最近 200 条任务事件与管理员操作')+table(['时间','事件','任务','说明'],list.map(x=>`<tr><td>${date(x.at)}</td><td>${esc(x.kind)}</td><td>${esc(x.task_id)||'—'}</td><td>${esc(x.detail)||'—'}</td></tr>`))}
function settings(){const s=state.settings;return heading('调度设置','修改后立即生效；当前执行超时也使用最新设置')+`<form class="panel settings" onsubmit="saveSettings(event)"><label>队列容量<input name="max_queue" type="number" min="1" max="500" value="${s.max_queue}" required></label><label>单次执行超时（秒）<input name="execution_timeout" type="number" min="60" max="86400" value="${s.execution_timeout}" required></label><label>手动重试最大次数<input name="max_retries" type="number" min="0" max="10" value="${s.max_retries}" required></label><p class="note">超时会暂停后续调度，避免 ComfyUI 未结束时重复分配。重试不会自动执行，需要管理员从失败任务发起。</p><button class="primary">保存设置</button></form>`}
async function saveSettings(e){e.preventDefault();const data={...state.settings};for(const [k,v] of new FormData(e.target))data[k]=Number(v);confirmAction('将这些调度设置立即应用到服务器？','/settings',data,'PUT')}
let renderEpoch=0;
async function render(){if(!state||!loggedIn)return;const epoch=++renderEpoch;route=location.hash.slice(1)||'overview';if(!pages[route])route='overview';nav();try{const html=await ({overview,tasks:()=>taskPage(),queue:()=>taskPage(true),workers,users,keys,usage,logs,settings}[route])();if(epoch===renderEpoch)$('#app').innerHTML=html}catch(e){toast(e.message)}}
window.addEventListener('hashchange',()=>{query='';render()});$('#detail').addEventListener('click',e=>{if(e.target===$('#detail'))closeDetail()});
refresh(false).then(()=>{if(loggedIn)refreshTimer=setInterval(()=>refresh(false),15000);else loginView()});
